import type { GrammarConcept } from '../../core/types'

export const week1Grammar: GrammarConcept[] = [
  {
    id: 'pronouns',
    label: 'Subject Pronouns',
    cefr: 'A1.1',
    explanation: 'I, you, he, she, it, we, they — the subject of a sentence.',
    examples: ['I am here.', 'She is a teacher.', 'They are students.'],
    commonMistakes: [
      { wrong: 'he is name Marc', right: 'his name is Marc', why: '"He" is a subject pronoun; use "his" as a possessive.' },
    ],
    triggerWords: [],
    prerequisites: [],
    masteryThreshold: 70,
  },
  {
    id: 'be',
    label: 'Verb "to be"',
    cefr: 'A1.1',
    explanation: 'am / is / are — used for identity, state, and description.',
    examples: ['I am from France.', 'You are right.', 'It is cold today.'],
    commonMistakes: [
      { wrong: 'I is happy', right: 'I am happy', why: '"I" always takes "am", never "is".' },
      { wrong: 'She are tired', right: 'She is tired', why: '"She/he/it" take "is", not "are".' },
    ],
    triggerWords: [],
    prerequisites: ['pronouns'],
    masteryThreshold: 75,
  },
  {
    id: 'have',
    label: 'Verb "to have"',
    cefr: 'A1.1',
    explanation: 'have / has — possession, relationships, and basic states.',
    examples: ['I have two brothers.', 'She has a car.', 'We have time.'],
    commonMistakes: [
      { wrong: 'she have a car', right: 'she has a car', why: 'With he/she/it, "have" becomes "has".' },
    ],
    triggerWords: [],
    prerequisites: ['pronouns'],
    masteryThreshold: 75,
  },
  {
    id: 'possessives',
    label: 'Possessive Adjectives',
    cefr: 'A1.1',
    explanation: 'my, your, his, her, its, our, their — showing ownership.',
    examples: ['This is my phone.', 'Her name is Anna.', 'Their house is big.'],
    commonMistakes: [
      { wrong: 'his name is... she is a doctor', right: 'her name is... she is a doctor', why: 'Use "her" for a female possessor, not "his".' },
    ],
    triggerWords: [],
    prerequisites: ['pronouns'],
    masteryThreshold: 70,
  },
  {
    id: 'present_simple_basic',
    label: 'Present Simple (basic)',
    cefr: 'A1.2',
    explanation: 'Regular action verbs for facts and routines: I work, I live, I like.',
    examples: ['I work in Kinshasa.', 'I live with my family.', 'I like coffee.'],
    commonMistakes: [
      { wrong: 'she work here', right: 'she works here', why: 'Add "-s" for he/she/it in the present simple.' },
    ],
    triggerWords: ['every day', 'usually', 'always'],
    prerequisites: ['pronouns', 'be'],
    masteryThreshold: 70,
  },
  {
    id: 'articles',
    label: 'Articles: a / an / the',
    cefr: 'A1.1',
    explanation: '"a/an" for one unspecified thing, "the" for something specific or known.',
    examples: ['I have a car.', 'She is an engineer.', 'The car is red.'],
    commonMistakes: [
      { wrong: 'she is a engineer', right: 'she is an engineer', why: 'Use "an" before a vowel sound.' },
    ],
    triggerWords: [],
    prerequisites: [],
    masteryThreshold: 65,
  },
  {
    id: 'plural_nouns',
    label: 'Singular / Plural Nouns',
    cefr: 'A1.1',
    explanation: 'Add "-s" or "-es" to make most nouns plural.',
    examples: ['one book, two books', 'one box, two boxes', 'one child, two children'],
    commonMistakes: [
      { wrong: 'two child', right: 'two children', why: '"Child" has an irregular plural: children.' },
    ],
    triggerWords: [],
    prerequisites: [],
    masteryThreshold: 65,
  },
  {
    id: 'there_is_are',
    label: 'There is / There are',
    cefr: 'A1.1',
    explanation: 'Use "there is" for one thing, "there are" for more than one.',
    examples: ['There is a table.', 'There are three chairs.', 'Is there a problem?'],
    commonMistakes: [
      { wrong: 'there is three chairs', right: 'there are three chairs', why: 'Plural nouns need "there are", not "there is".' },
    ],
    triggerWords: [],
    prerequisites: ['be', 'plural_nouns'],
    masteryThreshold: 70,
  },
  {
    id: 'basic_questions',
    label: 'Basic Questions',
    cefr: 'A1.1',
    explanation: 'Yes/no questions with "be" and "do", and simple wh-questions.',
    examples: ['Are you ready?', 'Do you work here?', 'What is your name?'],
    commonMistakes: [
      { wrong: 'you are ready?', right: 'are you ready?', why: 'Invert subject and verb to form a yes/no question.' },
    ],
    triggerWords: [],
    prerequisites: ['be', 'pronouns'],
    masteryThreshold: 65,
  },
  {
    id: 'basic_negatives',
    label: 'Basic Negatives',
    cefr: 'A1.1',
    explanation: "Use \"don't/doesn't\" with action verbs, and \"am not/isn't/aren't\" with be.",
    examples: ["I don't work on Sundays.", "She doesn't like coffee.", "I'm not ready."],
    commonMistakes: [
      { wrong: 'she not like coffee', right: "she doesn't like coffee", why: 'Use "doesn\'t" to negate an action verb with he/she/it.' },
    ],
    triggerWords: [],
    prerequisites: ['present_simple_basic'],
    masteryThreshold: 65,
  },
]
