import type { UsageNote } from '../core/types'

export const week1UsageNotes: UsageNote[] = [
  {
    id: 'un-a-an',
    title: '"a" vs "an"',
    cefr: 'A1.1',
    relatedGrammar: ['articles'],
    explanation: 'Use "an" before a vowel SOUND, not just a vowel letter. "an hour" (silent h) but "a university" (sounds like "yoo").',
    examplesGood: ['an engineer', 'an hour', 'a university', 'a car'],
    examplesBad: ['a engineer', 'a hour', 'an university'],
  },
  {
    id: 'un-am-is-are',
    title: '"am" vs "is" vs "are"',
    cefr: 'A1.1',
    relatedGrammar: ['be', 'pronouns'],
    explanation: '"am" only ever follows "I". "is" follows he/she/it or a singular noun. "are" follows you/we/they or a plural noun. Never mix them.',
    examplesGood: ['I am ready.', 'She is ready.', 'They are ready.'],
    examplesBad: ['I is ready.', 'She are ready.', 'They is ready.'],
  },
  {
    id: 'un-do-does',
    title: '"do" vs "does" in questions',
    cefr: 'A1.2',
    relatedGrammar: ['basic_questions', 'present_simple_basic'],
    explanation: 'Use "does" with he/she/it — and when you use "does", the main verb loses its "-s": "Does she work here?", not "Does she works here?".',
    examplesGood: ['Do you work here?', 'Does she work here?'],
    examplesBad: ['Does she works here?', 'Do she work here?'],
  },
  {
    id: 'un-there-is-are',
    title: '"there is" vs "there are"',
    cefr: 'A1.1',
    relatedGrammar: ['there_is_are'],
    explanation: 'Match "there is/are" to what comes right after it, not to the topic of the sentence. "There are three chairs and a table" — plural wins if the first noun after it is plural.',
    examplesGood: ['There is a table.', 'There are three chairs.'],
    examplesBad: ['There is three chairs.'],
  },
  {
    id: 'un-negative-verb',
    title: "\"don't/doesn't\" vs \"am not/isn't/aren't\"",
    cefr: 'A1.1',
    relatedGrammar: ['basic_negatives'],
    explanation: 'Action verbs (work, like, live) need "don\'t/doesn\'t". The verb "be" never uses "don\'t" — it negates directly: "I am not", "she isn\'t", never "I don\'t am" or "she don\'t like".',
    examplesGood: ["I don't work on Sundays.", "She isn't ready.", "I'm not sure."],
    examplesBad: ["I don't am ready.", "She don't like coffee."],
  },
  {
    id: 'un-possessive-vs-subject',
    title: '"her" vs "she"',
    cefr: 'A1.1',
    relatedGrammar: ['possessives', 'pronouns'],
    explanation: '"She" is the subject doing the action. "Her" shows possession or is the object. A common slip: using "she" as a possessive.',
    examplesGood: ["She is a doctor.", "Her name is Anna.", "I called her."],
    examplesBad: ['She name is Anna.'],
  },
]

export const week2UsageNotes: UsageNote[] = [
  {
    id: 'un-s-es-ies',
    title: '-s, -es or -ies with he / she / it?',
    cefr: 'A1.2',
    relatedGrammar: ['present_simple_third_person'],
    explanation: 'Most verbs just add -s (works). Verbs ending in s, sh, ch, x or o add -es (watches, finishes, goes). Consonant + y becomes -ies (study → studies), but vowel + y just adds -s (play → plays).',
    examplesGood: ['She works.', 'He watches TV.', 'It goes fast.', 'She studies.', 'He plays.'],
    examplesBad: ['He watchs TV.', 'She studys.'],
  },
  {
    id: 'un-frequency-position',
    title: 'Where does "always" go?',
    cefr: 'A1.2',
    relatedGrammar: ['frequency_adverbs'],
    explanation: 'Before the main verb ("I always drink tea") but after "be" ("She is always happy"). French speakers often put it at the end, which sounds wrong in English.',
    examplesGood: ['I always drink tea.', 'She is always happy.', 'They never work on Sunday.'],
    examplesBad: ['I drink always tea.', 'She always is happy.'],
  },
  {
    id: 'un-at-on-in-time',
    title: 'at / on / in for time',
    cefr: 'A1.2',
    relatedGrammar: ['prepositions_time'],
    explanation: 'Think of it as precise → general: "at" for exact clock times (at 7:30, at noon, at night), "on" for days and dates (on Monday, on May 3rd), "in" for longer periods (in the morning, in July, in 2026).',
    examplesGood: ['at 7:30', 'on Monday', 'in the morning', 'in July', 'at night'],
    examplesBad: ['on 7:30', 'in Monday', 'at the morning'],
  },
  {
    id: 'un-at-home-work',
    title: '"at home", "at work" — fixed expressions',
    cefr: 'A1.2',
    relatedGrammar: ['prepositions_place'],
    explanation: 'Usual places use "at" without an article: at home, at work, at school. After motion verbs, "home" takes no preposition at all: "I go home", not "I go to home".',
    examplesGood: ['I am at home.', 'She is at work.', 'I go home at six.'],
    examplesBad: ['I am in home.', 'I go to home.'],
  },
  {
    id: 'un-good-well',
    title: '"good" vs "well"',
    cefr: 'A1.2',
    relatedGrammar: ['adverbs_manner'],
    explanation: '"good" describes a noun (a good teacher). "well" describes an action (she teaches well). In French both are "bien", which is why this one is so easy to mix up.',
    examplesGood: ['She is a good driver.', 'She drives well.', 'He speaks English well.'],
    examplesBad: ['She drives good.', 'He speaks English good.'],
  },
]

export const week3UsageNotes: UsageNote[] = [
  {
    id: 'un-was-were',
    title: '"was" vs "were"',
    cefr: 'A2.1',
    relatedGrammar: ['past_simple_be'],
    explanation: '"was" for I / he / she / it, "were" for you / we / they. Only "be" changes like this: every other verb has one past form for all subjects.',
    examplesGood: ['I was late.', 'She was at home.', 'You were right.', 'They were tired.'],
    examplesBad: ['I were late.', 'They was tired.'],
  },
  {
    id: 'un-ed-sounds',
    title: 'How to say -ed: three sounds',
    cefr: 'A2.1',
    relatedGrammar: ['past_simple_regular'],
    explanation: 'The -ed ending is NOT always "ed". After a voiceless sound it is /t/ (worked, watched), after a voiced sound it is /d/ (played, called), and only after t or d is it a full syllable /id/ (wanted, needed). Listen to the audio and repeat.',
    examplesGood: ['worked = "workt"', 'played = "playd"', 'wanted = "wanted" (2 syllables)'],
    examplesBad: ['worked = "work-ed"', 'played = "play-ed"'],
  },
  {
    id: 'un-ed-spelling',
    title: 'Spelling the -ed form',
    cefr: 'A2.1',
    relatedGrammar: ['past_simple_regular'],
    explanation: 'Verb ends in -e: add -d (like → liked). Consonant + y: change y to -ied (study → studied). One vowel + one consonant, stressed: double it (stop → stopped). Vowel + y: just add -ed (play → played).',
    examplesGood: ['liked', 'studied', 'stopped', 'played'],
    examplesBad: ['likeed', 'studyed', 'stoped', 'playied'],
  },
  {
    id: 'un-no-goed',
    title: 'Irregular verbs: no "-ed" allowed',
    cefr: 'A2.1',
    relatedGrammar: ['past_simple_irregular'],
    explanation: 'French speakers often "regularize" irregular verbs (goed, taked, buyed). The most frequent verbs are irregular precisely because they are so old and so common: go/went, have/had, see/saw, take/took, make/made. Learn them as pairs inside a sentence.',
    examplesGood: ['I went home.', 'She took a taxi.', 'We bought tickets.'],
    examplesBad: ['I goed home.', 'She taked a taxi.', 'We buyed tickets.'],
  },
  {
    id: 'un-read-past',
    title: '"read": same spelling, different sound',
    cefr: 'A2.1',
    relatedGrammar: ['past_simple_irregular'],
    explanation: 'Present "read" rhymes with "need" (/riːd/). Past "read" is spelled the same but sounds like "red" (/rɛd/). Only context tells you which one it is.',
    examplesGood: ['I read every day. (reed)', 'I read the report yesterday. (red)'],
    examplesBad: [],
  },
  {
    id: 'un-did-base',
    title: 'After "did" / "didn\'t", go back to the base verb',
    cefr: 'A2.1',
    relatedGrammar: ['past_simple_negatives', 'past_simple_questions'],
    explanation: 'The past is shown once, on "did". So the main verb stays in its base form: "Did you go?", "I didn\'t see him". Putting the past on both ("did you went") is the most common mistake at this level.',
    examplesGood: ['Did you go?', "I didn't see him.", 'What did she say?'],
    examplesBad: ['Did you went?', "I didn't saw him.", 'What did she said?'],
  },
  {
    id: 'un-ago',
    title: '"ago" vs "last"',
    cefr: 'A2.1',
    relatedGrammar: ['past_time_expressions'],
    explanation: '"ago" comes AFTER a length of time counted back from now (two days ago). "last" comes BEFORE a period (last week, last year). Never use "since" or "il y a" word for word.',
    examplesGood: ['two days ago', 'last week', 'a long time ago'],
    examplesBad: ['ago two days', 'since two days', 'the last week (for a finished week)'],
  },
]

export const week4UsageNotes: UsageNote[] = [
  {
    id: 'un-continuous-vs-simple',
    title: 'Background vs. event: continuous vs. simple',
    cefr: 'A2.2',
    relatedGrammar: ['when_interrupted_action', 'storytelling_mixed'],
    explanation: 'The past continuous paints the scene (what was already going on); the past simple is the event that happens inside that scene. "I was walking (scene) when I saw him (event)" — not the other way round.',
    examplesGood: ['I was walking when I saw him.', 'It was raining when we left.'],
    examplesBad: ['I walked when I was seeing him.'],
  },
  {
    id: 'un-when-vs-while',
    title: '"when" vs "while"',
    cefr: 'A2.2',
    relatedGrammar: ['when_interrupted_action', 'while_parallel_actions'],
    explanation: '"when" introduces the short interrupting event (+ past simple). "while" introduces a second action happening at the same time as another (+ past continuous on both sides, usually).',
    examplesGood: ['I was cooking when she arrived.', 'While I was cooking, she was setting the table.'],
    examplesBad: ['While she arrived, I was cooking.'],
  },
  {
    id: 'un-not-was-ing-alone',
    title: 'The past continuous always needs was/were',
    cefr: 'A2.2',
    relatedGrammar: ['past_continuous'],
    explanation: 'French "en train de" sometimes gets dropped in fast speech, but in English the -ing form can never stand alone as a full verb: "I working" is not a sentence. You always need was/were (or am/is/are in the present).',
    examplesGood: ['I was working.', 'She is working.'],
    examplesBad: ['I working.', 'She working.'],
  },
]

export const week5UsageNotes: UsageNote[] = [
  {
    id: 'un-will-vs-goingto',
    title: 'Already decided vs. deciding now',
    cefr: 'A2.3',
    relatedGrammar: ['will_vs_going_to'],
    explanation: 'If the plan exists before you speak (a booking, an arrangement), use "going to". If you are deciding at the exact moment you speak (an offer, a spontaneous choice, a reaction), use "will".',
    examplesGood: ["I'm going to visit my parents next week. (already planned)", "The phone's ringing — I'll get it. (deciding now)"],
    examplesBad: ["I'll visit my parents next week, it's already booked."],
  },
  {
    id: 'un-no-to-after-modal',
    title: 'No "to" after will / might / should',
    cefr: 'A2.3',
    relatedGrammar: ['future_will', 'modals_possibility', 'modals_advice'],
    explanation: 'will, might, may, should, must, can, could — none of them are ever followed by "to". They go straight to the base verb: "I will go", not "I will to go".',
    examplesGood: ['I will go.', 'I might come.', 'You should rest.'],
    examplesBad: ['I will to go.', 'I might to come.', 'You should to rest.'],
  },
  {
    id: 'un-should-vs-must',
    title: '"should" (advice) vs "must" (obligation)',
    cefr: 'A2.3',
    relatedGrammar: ['modals_advice'],
    explanation: '"should" is a friendly suggestion — the person can choose to ignore it. "must" is a strong obligation or rule. Mixing them up can sound much more forceful than you mean.',
    examplesGood: ['You should try this restaurant. (suggestion)', 'You must wear a seatbelt. (rule)'],
    examplesBad: ['You must try this restaurant. (too strong for a friendly tip)'],
  },
  {
    id: 'un-present-continuous-future',
    title: 'Present continuous ≠ present action, here',
    cefr: 'A2.3',
    relatedGrammar: ['present_continuous_future'],
    explanation: 'With a future time word (tomorrow, on Monday, next week), "I\'m meeting him" is NOT happening right now — it describes a fixed future arrangement. Context (the time word) tells you it\'s the future, not the grammar form itself.',
    examplesGood: ["I'm meeting a client tomorrow.", "We're flying to Paris on Monday."],
    examplesBad: [],
  },
]
