import type { BossMission, Mission } from '../../core/types'

export const week1Missions: Mission[] = [
  {
    id: 'day-01', day: 1, week: 1, cefr: 'A1.1', title: 'Foundation — I am, I have',
    isBoss: false,
    grammarFocus: ['pronouns', 'be'],
    vocabularyFocus: ['v-name', 'v-from', 'v-country', 'v-city'],
    weakSpotSlots: 0,
    sections: [
      { kind: 'warmup', label: 'Warm-up', durationMinutes: 2, exerciseIds: ['d1-ex1', 'd1-ex2'] },
      { kind: 'grammar_reflex', label: 'Grammar Reflex', durationMinutes: 4, exerciseIds: ['d1-ex3', 'd1-reflex1', 'd1-reflex2'] },
      { kind: 'vocabulary', label: 'Vocabulary', durationMinutes: 3, exerciseIds: [] },
      { kind: 'speaking', label: 'Speaking', durationMinutes: 6, exerciseIds: ['d1-speak1'] },
      { kind: 'correction', label: 'Correction', durationMinutes: 3, exerciseIds: [] },
      { kind: 'review', label: 'Review', durationMinutes: 2, exerciseIds: [] },
    ],
  },
  {
    id: 'day-02', day: 2, week: 1, cefr: 'A1.1', title: 'Family & Possession',
    isBoss: false,
    grammarFocus: ['have', 'possessives'],
    vocabularyFocus: ['v-family', 'v-brother', 'v-sister', 'v-house'],
    weakSpotSlots: 1,
    sections: [
      { kind: 'warmup', label: 'Warm-up', durationMinutes: 2, exerciseIds: ['d2-ex1', 'd2-ex2'] },
      { kind: 'grammar_reflex', label: 'Grammar Reflex', durationMinutes: 4, exerciseIds: ['d2-ex3', 'd2-reflex1', 'd2-reflex2'] },
      { kind: 'vocabulary', label: 'Vocabulary', durationMinutes: 3, exerciseIds: [] },
      { kind: 'speaking', label: 'Speaking', durationMinutes: 6, exerciseIds: ['d2-speak1'] },
      { kind: 'correction', label: 'Correction', durationMinutes: 3, exerciseIds: [] },
      { kind: 'review', label: 'Review', durationMinutes: 2, exerciseIds: [] },
    ],
  },
  {
    id: 'day-03', day: 3, week: 1, cefr: 'A1.2', title: 'Everyday Actions',
    isBoss: false,
    grammarFocus: ['present_simple_basic'],
    vocabularyFocus: ['v-job', 'v-company', 'v-colleague'],
    weakSpotSlots: 1,
    sections: [
      { kind: 'warmup', label: 'Warm-up', durationMinutes: 2, exerciseIds: ['d3-ex1', 'd3-ex2'] },
      { kind: 'grammar_reflex', label: 'Grammar Reflex', durationMinutes: 4, exerciseIds: ['d3-ex3', 'd3-reflex1', 'd3-reflex2'] },
      { kind: 'vocabulary', label: 'Vocabulary', durationMinutes: 3, exerciseIds: [] },
      { kind: 'speaking', label: 'Speaking', durationMinutes: 6, exerciseIds: ['d3-speak1'] },
      { kind: 'correction', label: 'Correction', durationMinutes: 3, exerciseIds: [] },
      { kind: 'review', label: 'Review', durationMinutes: 2, exerciseIds: [] },
    ],
  },
  {
    id: 'day-04', day: 4, week: 1, cefr: 'A1.1', title: 'One, Many, and What\'s There',
    isBoss: false,
    grammarFocus: ['articles', 'plural_nouns', 'there_is_are'],
    vocabularyFocus: ['v-house', 'v-apartment', 'v-city', 'v-country'],
    weakSpotSlots: 1,
    sections: [
      { kind: 'warmup', label: 'Warm-up', durationMinutes: 2, exerciseIds: ['d4-ex1', 'd4-ex2'] },
      { kind: 'grammar_reflex', label: 'Grammar Reflex', durationMinutes: 4, exerciseIds: ['d4-ex3', 'd4-reflex1', 'd4-reflex2'] },
      { kind: 'vocabulary', label: 'Vocabulary', durationMinutes: 3, exerciseIds: [] },
      { kind: 'speaking', label: 'Speaking', durationMinutes: 6, exerciseIds: ['d4-speak1'] },
      { kind: 'correction', label: 'Correction', durationMinutes: 3, exerciseIds: [] },
      { kind: 'review', label: 'Review', durationMinutes: 2, exerciseIds: [] },
    ],
  },
  {
    id: 'day-05', day: 5, week: 1, cefr: 'A1.1', title: 'Asking Questions',
    isBoss: false,
    grammarFocus: ['basic_questions'],
    vocabularyFocus: ['v-today', 'v-morning', 'v-usually'],
    weakSpotSlots: 2,
    sections: [
      { kind: 'warmup', label: 'Warm-up', durationMinutes: 2, exerciseIds: ['d5-ex1', 'd5-ex2'] },
      { kind: 'grammar_reflex', label: 'Grammar Reflex', durationMinutes: 4, exerciseIds: ['d5-ex3', 'd5-reflex1', 'd5-reflex2'] },
      { kind: 'vocabulary', label: 'Vocabulary', durationMinutes: 3, exerciseIds: [] },
      { kind: 'speaking', label: 'Speaking', durationMinutes: 6, exerciseIds: ['d5-speak1'] },
      { kind: 'correction', label: 'Correction', durationMinutes: 3, exerciseIds: [] },
      { kind: 'review', label: 'Review', durationMinutes: 2, exerciseIds: [] },
    ],
  },
  {
    id: 'day-06', day: 6, week: 1, cefr: 'A1.1', title: 'Saying No, and Review',
    isBoss: false,
    grammarFocus: ['basic_negatives'],
    vocabularyFocus: ['v-yesterday', 'v-tomorrow'],
    weakSpotSlots: 2,
    sections: [
      { kind: 'warmup', label: 'Warm-up', durationMinutes: 2, exerciseIds: ['d6-ex1', 'd6-ex2'] },
      { kind: 'grammar_reflex', label: 'Grammar Reflex', durationMinutes: 4, exerciseIds: ['d6-ex3', 'd6-reflex1', 'd6-reflex2'] },
      { kind: 'vocabulary', label: 'Vocabulary', durationMinutes: 3, exerciseIds: [] },
      { kind: 'speaking', label: 'Speaking', durationMinutes: 6, exerciseIds: ['d6-speak1'] },
      { kind: 'correction', label: 'Correction', durationMinutes: 3, exerciseIds: [] },
      { kind: 'review', label: 'Review', durationMinutes: 2, exerciseIds: [] },
    ],
  },
]

export const day7BossMission: BossMission = {
  id: 'day-07', day: 7, week: 1, cefr: 'A1.2', title: 'BOSS — Introduce Yourself',
  isBoss: true,
  bossPrompt: 'Introduce yourself for 60 seconds: name, origin, job, family, and something you like.',
  evaluatedSkills: ['grammar', 'vocabulary', 'speaking', 'fluency'],
  grammarFocus: ['pronouns', 'be', 'have', 'present_simple_basic', 'articles', 'there_is_are', 'basic_questions', 'basic_negatives'],
  vocabularyFocus: ['v-name', 'v-from', 'v-family', 'v-job'],
  weakSpotSlots: 0,
  sections: [
    { kind: 'warmup', label: 'Warm-up', durationMinutes: 2, exerciseIds: [] },
    { kind: 'speaking', label: 'Boss Speaking', durationMinutes: 10, exerciseIds: ['d7-boss1'] },
    { kind: 'correction', label: 'Correction', durationMinutes: 4, exerciseIds: [] },
    { kind: 'review', label: 'Results', durationMinutes: 2, exerciseIds: [] },
  ],
}
